# Buildpack API version
api = "0.8"

# Buildpack ID and metadata
[buildpack]
  id = "examples/ruby"
  version = "0.0.1"
  sbom-formats = [ "application/vnd.cyclonedx+json" ]

# Stacks that the buildpack will work with
[[stacks]]
  id = "io.buildpacks.samples.stacks.bionic"